### ISSUE TITLE
program crashes out if you supply a filename but forget to add the -f flag

### ISSUE THREAD

**Issue by pemj** [packetsled/bro_intel_linter#3]
I think the issue is in the option parser.  I'm currently working on a fork that uses the argparse library instead of optparse, but I'm also converting it to python3, and I have not yet tested it exhaustively to determine if there are any other issues lurking around.  If I get it stable in the next few days, I'll submit a pull request.

**Comment by aeppert** [comment]
Be warned, Python 3 will likely not be directly merged. Where this is used, fundamentally for me and others are Python 2.6 and 2.7 environments by necessity. So, please make sure any pull requests around Python 3 are backwards compatible. No sense moving it to Python 3 for the sake of it.
